FROM ubuntu:16.04

MAINTAINER Mike Mueller<mike@objektarium.de>

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
        openssh-client \
        bash \
        vim
        
CMD ["bash"]
